### ISSUE TITLE
Make dub executable

### ISSUE THREAD

**Issue by Timoses** [jacob-carlborg/dvm#44] opened 2018-12-13 13:15 UTC
I was surprised to not having to install dub separately as it's already contained in `~/.dvm/compilers/dmd-2.0xx.x/linux/bin/dub`
after using
```
./dvm install dvm
dvm install 2.083.1
dvm use 2.083.1
```
However, it is not executable which means I had to run
```
chmod u+x ~/.dvm/compilers/dmd-2.0xx.x/linux/bin/dub
```

Would be cool if this happened automatically during the installation process.

**Comment by jacob-carlborg** [comment] 2018-12-13 18:44
Yes, definitely. The problem is that DVM use Tango, which is not maintained anymore. I need to try to find an old enough compiler that will work.

Ideally DVM should be completely rewritten to not use Phobos instead of Tango but that's a big effort.

**Comment by jacob-carlborg** [comment] 2019-03-31 19:06
Fixed in https://github.com/jacob-carlborg/dvm/commit/059c1a8789ecfff8bf1d38e778f21ec26f994a85.

**Closed by jacob-carlborg** 2019-03-31 19:06 UTC
